name = "Topfdeckel"
license = "MIT"
licenselink = "https://github.com/gaim-dev/topfdeckel/blob/master/LICENSE.md"
description = "The Hugo theme for kochfokus.de"
homepage = "https://kochfokus.de"
min_version = "0.27"

[author]
  name = "Benjamin Altpeter"
  homepage = "https://benjamin-altpeter.de"
